namespace tsql_formatter;

internal class Keywords
{
  public const string ALL = "ALL";
  public const string AND = "AND";
  public const string AS = "AS";
  public const string ASC = "ASC";
  public const string AT_TIME_ZONE = "AT TIME ZONE";
  public const string BETWEEN = "BETWEEN";
  public const string CASE = "CASE";
  public const string COLLATE = "COLLATE";
  public const string CROSS_APPLY = "CROSS APPLY";
  public const string CROSS_JOIN = "CROSS JOIN";
  public const string CUBE = "CUBE";
  public const string DEFAULT = "DEFAULT";
  public const string DELETE = "DELETE";
  public const string DESC = "DESC";
  public const string DISTINCT = "DISTINCT";
  public const string ELSE = "ELSE";
  public const string END = "END";
  public const string ESCAPE = "ESCAPE";
  public const string EXCEPT = "EXCEPT";
  public const string FETCH_NEXT = "FETCH NEXT";
  public const string FROM = "FROM";
  public const string FULL_OUTER_JOIN = "FULL OUTER JOIN";
  public const string GROUP_BY = "GROUP BY";
  public const string HAVING = "HAVING";
  public const string INNER_JOIN = "INNER JOIN";
  public const string INTERSECT = "INTERSECT";
  public const string INTO = "INTO";
  public const string IS_NOT_NULL = "IS NOT NULL";
  public const string IS_NULL = "IS NULL";
  public const string LEFT_OUTER_JOIN = "LEFT OUTER JOIN";
  public const string LIKE = "LIKE";
  public const string MAX = "MAX";
  public const string NOT = "NOT";
  public const string NULL = "NULL";
  public const string OFFSET = "OFFSET";
  public const string ON = "ON";
  public const string OR = "OR";
  public const string ORDER_BY = "ORDER BY";
  public const string OUTER_APPLY = "OUTER APPLY";
  public const string PERCENT = "PERCENT";
  public const string RIGHT_OUTER_JOIN = "RIGHT OUTER JOIN";
  public const string ROWS = "ROWS";
  public const string ROWS_ONLY = "ROWS ONLY";
  public const string SELECT = "SELECT";
  public const string THEN = "THEN";
  public const string TOP = "TOP";
  public const string UNION = "UNION";
  public const string UNION_ALL = "UNION ALL";
  public const string WHEN = "WHEN";
  public const string WHERE = "WHERE";
  public const string WITH = "WITH";
  public const string WITH_TIES = "WITH TIES";
}
